//! Command-bus tests. Transport adapters are tested in their own apps.

use std::io::{Read, Write};
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::process::Command as ProcessCommand;
use std::thread;
use std::time::{SystemTime, UNIX_EPOCH};

use wvq_command_bus::{
    BusError, Command, ContextCommand, EvidenceCommand, ExplainCommand, FakeService, INLINE_LIMIT,
    LiveService, ModelCommand, PlanCommand, QualityService, Reply, RunCommand, SelectCommand,
    SpecCommand, VerifyCommand, dispatch, estimate_tokens,
};

fn fixture_repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("fixtures")
        .join("openspec")
        .join("repo")
}

struct TempRepo(PathBuf);

impl Drop for TempRepo {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

fn live_runner_repo() -> TempRepo {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock")
        .as_nanos();
    let root = std::env::temp_dir().join(format!("wvq-live-runner-{nanos}"));
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::create_dir_all(root.join("openspec/changes/live-add/specs/arithmetic")).unwrap();
    std::fs::create_dir_all(root.join(".weavatrix-quality")).unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[workspace]\n\n[package]\nname = \"wvq-live-fixture\"\nversion = \"0.0.0\"\nedition = \"2024\"\n",
    )
    .unwrap();
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn add(a: i32, b: i32) -> i32 { a + b }\n",
    )
    .unwrap();
    std::fs::create_dir_all(root.join("tests")).unwrap();
    std::fs::write(
        root.join("tests/addition.rs"),
        "use wvq_live_fixture::add;\n\n#[test]\nfn adds() { assert_eq!(add(2, 3), 5); }\n",
    )
    .unwrap();
    std::fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"wvq-live-fixture\"\nversion = \"0.0.0\"\n",
    )
    .unwrap();
    std::fs::write(
        root.join("openspec/changes/live-add/specs/arithmetic/spec.md"),
        "# Delta for Arithmetic\n\n## ADDED Requirements\n\n### Requirement: Addition\nThe system SHALL add two integers.\n\n#### Scenario: Sum\n- GIVEN two integers\n- WHEN addition is requested\n- THEN their sum is returned\n",
    )
    .unwrap();
    std::fs::write(
        root.join("openspec/changes/live-add/quality.yaml"),
        "quality_contract_v: 1\nchange: live-add\n\nrisk:\n  default: low\n\nrequirements:\n  - capability: arithmetic\n    requirement: addition\n    scenarios:\n      - scenario: sum\n        obligations:\n          - id: addition-suite\n            kind: invariant\n        evidence:\n          required: []\n          on_failure: []\n\nai:\n  planning_tokens: 100\n  runtime_tokens: 0\n",
    )
    .unwrap();
    std::fs::write(
        root.join(".weavatrix-quality/config.yaml"),
        "quality_policy_v: 1\n\ntest_bindings:\n  - path: tests/addition.rs\n    obligations: [addition-suite]\n    cost: 10\n    flake_penalty: 0\n",
    )
    .unwrap();
    git(&root, &["init", "-q"]);
    git(&root, &["add", "-A"]);
    git(
        &root,
        &[
            "-c",
            "user.name=WVQ Test",
            "-c",
            "user.email=wvq@example.invalid",
            "commit",
            "-qm",
            "baseline",
        ],
    );
    TempRepo(root)
}

fn git(root: &Path, args: &[&str]) {
    let output = ProcessCommand::new("git")
        .args(args)
        .current_dir(root)
        .output()
        .expect("git starts");
    assert!(
        output.status.success(),
        "git {}: {}",
        args.join(" "),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn read_http_request(stream: &mut impl Read) -> Vec<u8> {
    let mut request = Vec::new();
    let mut buffer = [0_u8; 1024];
    let mut expected = None;
    loop {
        let read = stream.read(&mut buffer).unwrap();
        assert_ne!(read, 0, "request closed before its body was complete");
        request.extend_from_slice(&buffer[..read]);
        if expected.is_none()
            && let Some(split) = request.windows(4).position(|window| window == b"\r\n\r\n")
        {
            let head = String::from_utf8_lossy(&request[..split]);
            let content_length = head
                .lines()
                .find_map(|line| {
                    line.strip_prefix("Content-Length:")
                        .and_then(|value| value.trim().parse::<usize>().ok())
                })
                .unwrap();
            expected = Some(split + 4 + content_length);
        }
        if expected.is_some_and(|expected| request.len() >= expected) {
            return request;
        }
    }
}

#[test]
fn context_reply_is_bounded_by_token_budget() {
    let fake = FakeService::default();
    fake.set_context_items(vec![
        "requirement alpha is a long neighbouring clause about overflow".into(),
        "requirement beta is another neighbouring clause about grouping".into(),
        "obligation others-visible".into(),
        "heuristic: 0 runtime LLM tokens".into(),
    ]);
    let reply = fake
        .context(&ContextCommand {
            change: "sankey-others".into(),
            purpose: "implementation".into(),
            token_budget: 8,
        })
        .unwrap();
    assert!(reply.truncated);
    assert!(reply.tokens_used <= 8);
    let total = reply.requirements.len()
        + reply.obligations.len()
        + reply.heuristics.len()
        + reply.coverage.len();
    assert!(total < 4, "budget must drop later items");
}

#[test]
fn unknown_purpose_fails_closed() {
    let fake = FakeService::default();
    let err = fake
        .context(&ContextCommand {
            change: "sankey-others".into(),
            purpose: "vibes".into(),
            token_budget: 4000,
        })
        .unwrap_err();
    assert!(matches!(
        err,
        BusError::Unknown {
            field: "purpose",
            ..
        }
    ));
}

#[test]
fn plan_does_not_execute() {
    let fake = FakeService::default();
    let reply = fake
        .plan(&PlanCommand {
            change: "sankey-others".into(),
        })
        .unwrap();
    assert!(!reply.executed);
    assert!(!fake.run_was_executed());
    let _ = fake
        .run(&RunCommand {
            change: "sankey-others".into(),
            scope: "impacted".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert!(fake.run_was_executed());
}

#[test]
fn unknown_scope_fails_closed() {
    let fake = FakeService::default();
    let err = fake
        .run(&RunCommand {
            change: "current".into(),
            scope: "everything-everywhere".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap_err();
    assert!(matches!(err, BusError::Unknown { field: "scope", .. }));
}

#[test]
fn large_evidence_is_handle_only() {
    let fake = FakeService::default();
    let blob = vec![b'x'; INLINE_LIMIT + 16];
    fake.put_evidence("cas:big", blob);
    let reply = fake
        .evidence(&EvidenceCommand {
            handle: "cas:big".into(),
        })
        .unwrap();
    assert_eq!(reply.handle, "cas:big");
    assert!(reply.byte_len > INLINE_LIMIT as u64);
    assert!(reply.inline_text.is_none());
    assert!(reply.content_hash.is_some());
}

#[test]
fn small_utf8_evidence_is_inlined() {
    let fake = FakeService::default();
    fake.put_evidence("cas:tiny", b"junit snippet".to_vec());
    let reply = fake
        .evidence(&EvidenceCommand {
            handle: "cas:tiny".into(),
        })
        .unwrap();
    assert_eq!(reply.inline_text.as_deref(), Some("junit snippet"));
}

#[test]
fn contradicted_verify_is_blocking() {
    let fake = FakeService::default();
    fake.set_verdict("CONTRADICTED");
    let reply = dispatch(
        &fake,
        Command::Verify(VerifyCommand {
            change: "sankey-others".into(),
        }),
    )
    .unwrap();
    let Reply::Verify(body) = reply else {
        panic!("expected verify reply");
    };
    assert!(body.blocking);
    assert_eq!(body.exit_code(), 2);
    assert_eq!(body.verdict, "CONTRADICTED");
}

#[test]
fn proven_verify_is_zero_exit() {
    let fake = FakeService::default();
    fake.set_verdict("PROVEN");
    let reply = fake
        .verify(&VerifyCommand {
            change: "sankey-others".into(),
        })
        .unwrap();
    assert!(!reply.blocking);
    assert_eq!(reply.exit_code(), 0);
}

#[test]
fn explain_unknown_id_is_not_found() {
    let fake = FakeService::default();
    let err = fake
        .explain(&ExplainCommand {
            id: "missing".into(),
        })
        .unwrap_err();
    assert!(matches!(err, BusError::NotFound(_)));
}

#[test]
fn live_spec_validate_and_seal_sankey_others() {
    let service = LiveService::new(fixture_repo());
    let change = SpecCommand {
        change: "sankey-others".into(),
    };
    let valid = service.spec_validate(&change).unwrap();
    assert!(valid.ok);
    assert_eq!(valid.change, "sankey-others");
    assert!(valid.obligations >= 4);
    let sealed = service.spec_seal(&change).unwrap();
    assert!(sealed.seal_id.starts_with("oseal-"));
    assert_eq!(sealed.digest.len(), 64);
}

#[test]
fn live_current_change_is_ambiguous_in_fixture_repo() {
    let service = LiveService::new(fixture_repo());
    let err = service
        .spec_validate(&SpecCommand {
            change: "current".into(),
        })
        .unwrap_err();
    assert!(matches!(err, BusError::Ambiguous(_)));
}

#[test]
fn live_verify_without_runtime_is_unproven_not_failed() {
    let service = LiveService::new(fixture_repo());
    let reply = service
        .verify(&VerifyCommand {
            change: "sankey-others".into(),
        })
        .unwrap();
    assert_eq!(reply.verdict, "UNPROVEN");
    assert!(!reply.blocking);
    assert_eq!(reply.exit_code(), 1);
    assert!(reply.proofs.iter().all(|item| item.verdict == "UNPROVEN"));
}

#[test]
fn live_select_unions_base_and_head_static_candidates() {
    let repo = live_runner_repo();
    std::fs::write(
        repo.0.join("src/lib.rs"),
        "pub fn add(a: i32, b: i32) -> i32 { a.saturating_add(b) }\n",
    )
    .unwrap();
    let service = LiveService::new(&repo.0);
    let reply = service
        .select(&SelectCommand {
            change: "live-add".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert!(!reply.executed);
    assert_eq!(
        reply.algorithm,
        "weavatrix-base-head-union+greedy-weighted-set-cover"
    );
    assert!(reply.revision.is_some());
    assert!(
        reply.selected.contains(&"tests/addition.rs".into()),
        "{:?}",
        reply.selected
    );
    assert!(reply.uncovered_mandatory.is_empty());
    assert!(reply.selection_complete);
}

#[test]
fn live_debt_uses_an_immutable_git_baseline() {
    let repo = live_runner_repo();
    let service = LiveService::new(&repo.0);
    let reply = service
        .debt(&wvq_command_bus::DebtCommand {
            change: "live-add".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert!(reply.comparison_present);
    assert!(reply.revision.is_some());
    assert_eq!(reply.new, 0);
    assert_eq!(reply.fixed, 0);
}

#[test]
fn live_run_accepts_an_exact_committed_pr_range() {
    let repo = live_runner_repo();
    std::fs::write(
        repo.0.join("src/lib.rs"),
        "/// Checked-in head.\npub fn add(a: i32, b: i32) -> i32 { a + b }\n",
    )
    .unwrap();
    git(&repo.0, &["add", "-A"]);
    git(
        &repo.0,
        &[
            "-c",
            "user.name=WVQ Test",
            "-c",
            "user.email=wvq@example.invalid",
            "commit",
            "-qm",
            "feature head",
        ],
    );
    let service = LiveService::new(&repo.0);
    let reply = service
        .run(&RunCommand {
            change: "live-add".into(),
            scope: "all".into(),
            evidence_policy: "minimal".into(),
            base: "HEAD~1".into(),
            head: "HEAD".into(),
        })
        .unwrap();
    assert_eq!(reply.base, "HEAD~1");
    assert_eq!(reply.head, "HEAD");
    assert_eq!(reply.outcome, "passed");
}

#[test]
fn explicit_committed_head_rejects_a_dirty_worktree() {
    let repo = live_runner_repo();
    std::fs::write(
        repo.0.join("src/lib.rs"),
        "pub fn add(a: i32, b: i32) -> i32 { a.saturating_add(b) }\n",
    )
    .unwrap();
    let service = LiveService::new(&repo.0);
    let err = service
        .select(&SelectCommand {
            change: "live-add".into(),
            base: "HEAD~1".into(),
            head: "HEAD".into(),
        })
        .unwrap_err();
    assert!(err.to_string().contains("dirty worktree"), "{err}");
}

#[test]
fn live_recovery_is_populated_from_git_and_weavatrix() {
    let repo = live_runner_repo();
    std::fs::write(
        repo.0.join("src/lib.rs"),
        "/// Checked implementation.\npub fn add(a: i32, b: i32) -> i32 { a.saturating_add(b) }\n",
    )
    .unwrap();
    let service = LiveService::new(&repo.0);
    let desk = service
        .recovery_desk("live-add", "HEAD", "WORKTREE")
        .unwrap();
    let packet = desk.packet().expect("live recovery packet");
    assert_eq!(packet.base_revision.len(), 40);
    assert!(packet.head_revision.contains("WORKTREE@"));
    assert!(!packet.code_delta_summary.changed_symbols.is_empty());
    assert!(!packet.capability_clusters.is_empty());
    assert_eq!(desk.review().change, "live-add");
}

#[test]
fn live_model_call_charges_persistent_per_change_budget() {
    let repo = live_runner_repo();
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let address = listener.local_addr().unwrap();
    std::fs::write(
        repo.0.join(".weavatrix-quality/config.yaml"),
        format!(
            "quality_policy_v: 1\n\ntest_bindings:\n  - path: tests/addition.rs\n    obligations: [addition-suite]\n    cost: 10\n    flake_penalty: 0\n\nai:\n  endpoint: http://{address}/v1/chat/completions\n  model: local-test\n  max_output_tokens: 8\n  max_tokens_per_change: 15\n  max_runtime_tokens: 100\n  max_browser_escape_calls: 1\n  max_vision_calls: 1\n  max_cost_micros: 100\n  input_micros_per_million: 1000000\n  output_micros_per_million: 2000000\n"
        ),
    )
    .unwrap();
    let server = thread::spawn(move || {
        let (mut stream, _) = listener.accept().unwrap();
        let request = read_http_request(&mut stream);
        assert!(
            String::from_utf8_lossy(&request).starts_with("POST /v1/chat/completions HTTP/1.1")
        );
        let body = br#"{"model":"local-test","choices":[{"message":{"content":"inspect boundary"}}],"usage":{"prompt_tokens":3,"completion_tokens":2}}"#;
        write!(
            stream,
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
            body.len()
        )
        .unwrap();
        stream.write_all(body).unwrap();
    });
    let first = LiveService::new(&repo.0)
        .model(&ModelCommand {
            change: "live-add".into(),
            kind: "planning".into(),
            prompt: "probe".into(),
        })
        .unwrap();
    server.join().unwrap();
    assert_eq!(first.text, "inspect boundary");
    assert_eq!(first.input_tokens + first.output_tokens, 5);
    assert_eq!(first.cost_micros, 7);

    let error = LiveService::new(&repo.0)
        .model(&ModelCommand {
            change: "live-add".into(),
            kind: "planning".into(),
            prompt: "second probe".into(),
        })
        .unwrap_err();
    assert!(matches!(error, BusError::Model(_)));
    assert!(error.to_string().contains("AI_BUDGET_EXHAUSTED"));
}

#[test]
fn live_plan_sets_executed_false() {
    let service = LiveService::new(fixture_repo());
    let reply = service
        .plan(&PlanCommand {
            change: "sankey-others".into(),
        })
        .unwrap();
    assert!(!reply.executed);
    assert!(!reply.gaps.is_empty());
    assert!(reply.checks.contains(&"coverage".into()));
}

#[test]
fn live_run_rejects_a_repo_without_a_supported_runner() {
    let service = LiveService::new(fixture_repo());
    let err = service
        .run(&RunCommand {
            change: "sankey-others".into(),
            scope: "impacted".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap_err();
    assert!(
        err.to_string().contains("no supported registered executor"),
        "unexpected error: {err}"
    );
}

#[test]
#[allow(clippy::too_many_lines)]
fn live_run_executes_persists_and_proves_a_real_registered_suite() {
    let repo = live_runner_repo();
    std::fs::write(
        repo.0.join("src/lib.rs"),
        "/// Add two integers.\npub fn add(a: i32, b: i32) -> i32 { a + b }\n",
    )
    .unwrap();
    let service = LiveService::new(&repo.0);
    let reply = service
        .run(&RunCommand {
            change: "live-add".into(),
            scope: "impacted".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert!(reply.executed);
    assert_eq!(reply.outcome, "passed");
    assert_eq!(reply.requested_scope, "impacted");
    assert_eq!(reply.scope, "all", "incomplete selection must widen safely");
    assert!(
        reply
            .artifact_handles
            .iter()
            .any(|handle| handle.ends_with("-summary"))
    );
    assert!(
        reply
            .artifact_handles
            .iter()
            .any(|handle| handle.ends_with("-graph-diff"))
    );
    assert!(
        reply
            .artifact_handles
            .iter()
            .any(|handle| handle.ends_with("-impact"))
    );

    let reopened = LiveService::new(&repo.0);
    let status = reopened
        .status(&wvq_command_bus::StatusCommand {
            run_id: Some(reply.run_id.clone()),
        })
        .unwrap();
    assert_eq!(status.outcome.as_deref(), Some("passed"));
    assert_eq!(status.handles, reply.artifact_handles);

    let summary = reopened
        .evidence(&EvidenceCommand {
            handle: reply
                .artifact_handles
                .iter()
                .find(|handle| handle.ends_with("-summary"))
                .unwrap()
                .clone(),
        })
        .unwrap();
    assert_eq!(summary.kind, "execution-summary");
    assert!(
        summary
            .inline_text
            .as_deref()
            .unwrap()
            .contains("cargo-test")
    );

    let impact = reopened
        .evidence(&EvidenceCommand {
            handle: reply
                .artifact_handles
                .iter()
                .find(|handle| handle.ends_with("-impact"))
                .unwrap()
                .clone(),
        })
        .unwrap();
    assert_eq!(impact.kind, "impacted-surface");
    assert!(impact.inline_text.is_some());

    let verified = reopened
        .verify(&VerifyCommand {
            change: "live-add".into(),
        })
        .unwrap();
    assert_eq!(verified.verdict, "PROVEN");
    assert_eq!(verified.exit_code(), 0);

    let planned = reopened
        .plan(&PlanCommand {
            change: "live-add".into(),
        })
        .unwrap();
    assert_eq!(planned.existing_proofs.len(), 1);
    assert!(planned.gaps.is_empty(), "{:?}", planned.gaps);
    let proof = reopened
        .explain(&ExplainCommand {
            id: planned.existing_proofs[0].clone(),
        })
        .unwrap();
    assert_eq!(proof.kind, "proof");
    assert!(
        proof
            .provenance
            .iter()
            .any(|item| item.starts_with("revision "))
    );

    let run = reopened
        .explain(&ExplainCommand {
            id: reply.run_id.clone(),
        })
        .unwrap();
    assert_eq!(run.kind, "run");
    assert!(run.summary.contains("passed"));

    let selection = reopened
        .explain(&ExplainCommand {
            id: "tests/addition.rs".into(),
        })
        .unwrap();
    assert_eq!(selection.kind, "selection");
    assert!(!selection.provenance.is_empty());
}

#[test]
fn a_green_suite_without_an_obligation_binding_is_not_proof() {
    let repo = live_runner_repo();
    std::fs::remove_file(repo.0.join(".weavatrix-quality/config.yaml")).unwrap();
    git(&repo.0, &["add", "-A"]);
    git(
        &repo.0,
        &[
            "-c",
            "user.name=WVQ Test",
            "-c",
            "user.email=wvq@example.invalid",
            "commit",
            "-qm",
            "remove binding",
        ],
    );
    let service = LiveService::new(&repo.0);
    let run = service
        .run(&RunCommand {
            change: "live-add".into(),
            scope: "all".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert_eq!(run.outcome, "passed");

    let verified = service
        .verify(&VerifyCommand {
            change: "live-add".into(),
        })
        .unwrap();
    assert_eq!(verified.verdict, "UNPROVEN");
    assert_eq!(verified.exit_code(), 1);
}

#[test]
fn estimate_tokens_is_stable() {
    assert_eq!(estimate_tokens(""), 0);
    assert_eq!(estimate_tokens("abcd"), 1);
    assert_eq!(estimate_tokens("abcdefgh"), 2);
}
