//! Command-bus tests. Transport adapters are tested in their own apps.

use std::io::{Read, Write};
use std::net::TcpListener;
use std::path::{Path, PathBuf};
use std::process::Command as ProcessCommand;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use wvq_command_bus::{
    AuthorDraftCommand, AuthorPreviewCommand, AuthorPromoteCommand, AuthorValidateCommand, BusError,
    Command, ContextCommand, EvidenceCommand, ExplainCommand, FakeService, INLINE_LIMIT,
    LiveService, ModelCommand, PlanCommand, QualityService, Reply, RunCommand, SelectCommand,
    SpecCommand, VerifyCommand, dispatch, estimate_tokens,
};

fn fixture_repo() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("fixtures")
        .join("openspec")
        .join("repo")
}

struct TempRepo(PathBuf);

static NEXT_TEMP_REPO: AtomicU64 = AtomicU64::new(0);
static BROWSER_TEST_LOCK: Mutex<()> = Mutex::new(());

fn unique_temp_repo(prefix: &str) -> PathBuf {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock")
        .as_nanos();
    let sequence = NEXT_TEMP_REPO.fetch_add(1, Ordering::Relaxed);
    std::env::temp_dir().join(format!(
        "{prefix}-{}-{nanos}-{sequence}",
        std::process::id()
    ))
}

impl Drop for TempRepo {
    fn drop(&mut self) {
        let node_modules = self.0.join("node_modules");
        let links_outside = node_modules
            .canonicalize()
            .ok()
            .zip(self.0.canonicalize().ok())
            .is_some_and(|(target, root)| !target.starts_with(root));
        if links_outside {
            let _ = std::fs::remove_dir(&node_modules);
        }
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

fn live_runner_repo() -> TempRepo {
    let root = unique_temp_repo("wvq-live-runner");
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::create_dir_all(root.join("openspec/changes/live-add/specs/arithmetic")).unwrap();
    std::fs::create_dir_all(root.join(".weavatrix-quality")).unwrap();
    std::fs::write(
        root.join("Cargo.toml"),
        "[workspace]\n\n[package]\nname = \"wvq-live-fixture\"\nversion = \"0.0.0\"\nedition = \"2024\"\n",
    )
    .unwrap();
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn add(a: i32, b: i32) -> i32 { a + b }\n",
    )
    .unwrap();
    std::fs::create_dir_all(root.join("tests")).unwrap();
    std::fs::write(
        root.join("tests/addition.rs"),
        "use wvq_live_fixture::add;\n\n#[test]\nfn adds() { assert_eq!(add(2, 3), 5); }\n",
    )
    .unwrap();
    std::fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"wvq-live-fixture\"\nversion = \"0.0.0\"\n",
    )
    .unwrap();
    std::fs::write(
        root.join("openspec/changes/live-add/specs/arithmetic/spec.md"),
        "# Delta for Arithmetic\n\n## ADDED Requirements\n\n### Requirement: Addition\nThe system SHALL add two integers.\n\n#### Scenario: Sum\n- GIVEN two integers\n- WHEN addition is requested\n- THEN their sum is returned\n",
    )
    .unwrap();
    std::fs::write(
        root.join("openspec/changes/live-add/quality.yaml"),
        "quality_contract_v: 1\nchange: live-add\n\nrisk:\n  default: low\n\nrequirements:\n  - capability: arithmetic\n    requirement: addition\n    scenarios:\n      - scenario: sum\n        obligations:\n          - id: addition-suite\n            kind: invariant\n        evidence:\n          required: []\n          on_failure: []\n\nai:\n  planning_tokens: 100\n  runtime_tokens: 0\n",
    )
    .unwrap();
    std::fs::write(
        root.join(".weavatrix-quality/config.yaml"),
        "quality_policy_v: 1\n\ntest_bindings:\n  - path: tests/addition.rs\n    obligations: [addition-suite]\n    cost: 10\n    flake_penalty: 0\n",
    )
    .unwrap();
    git(&root, &["init", "-q"]);
    git(&root, &["add", "-A"]);
    git(
        &root,
        &[
            "-c",
            "user.name=WVQ Test",
            "-c",
            "user.email=wvq@example.invalid",
            "commit",
            "-qm",
            "baseline",
        ],
    );
    TempRepo(root)
}

fn live_coverage_runner_repo() -> TempRepo {
    let root = unique_temp_repo("wvq-live-coverage");
    std::fs::create_dir_all(root.join("src")).unwrap();
    std::fs::create_dir_all(root.join("openspec/changes/live-js/specs/arithmetic")).unwrap();
    std::fs::create_dir_all(root.join(".weavatrix-quality")).unwrap();
    std::fs::write(root.join(".gitignore"), "coverage/\n.weavatrix-quality/\n").unwrap();
    std::fs::write(
        root.join("package.json"),
        r#"{"name":"wvq-live-coverage","private":true,"type":"module","scripts":{"test":"node test.mjs"}}"#,
    )
    .unwrap();
    std::fs::write(
        root.join("src/add.js"),
        "export function add(a, b) {\n  return a + b;\n}\n",
    )
    .unwrap();
    std::fs::write(
        root.join("test.mjs"),
        "import fs from 'node:fs';\nimport { add } from './src/add.js';\nif (add(2, 3) !== 5) process.exit(1);\nfs.mkdirSync('coverage', { recursive: true });\nfs.writeFileSync('coverage/lcov.info', 'TN:\\nSF:src/add.js\\nDA:1,1\\nDA:2,1\\nend_of_record\\n');\n",
    )
    .unwrap();
    std::fs::write(
        root.join("openspec/changes/live-js/specs/arithmetic/spec.md"),
        "# Delta for Arithmetic\n\n## ADDED Requirements\n\n### Requirement: Addition\nThe system SHALL add two numbers.\n\n#### Scenario: Sum\n- GIVEN two numbers\n- WHEN addition is requested\n- THEN their sum is returned\n",
    )
    .unwrap();
    std::fs::write(
        root.join("openspec/changes/live-js/quality.yaml"),
        "quality_contract_v: 1\nchange: live-js\n\nrisk:\n  default: high\n\nrequirements:\n  - capability: arithmetic\n    requirement: addition\n    scenarios:\n      - scenario: sum\n        obligations:\n          - id: addition-behavior\n            kind: behavioral\n        evidence:\n          required: [coverage]\n          on_failure: []\n",
    )
    .unwrap();
    std::fs::write(
        root.join(".weavatrix-quality/config.yaml"),
        "quality_policy_v: 1\n\ntest_bindings:\n  - path: test.mjs\n    obligations: [addition-behavior]\n    cost: 10\n    flake_penalty: 0\n",
    )
    .unwrap();
    git(&root, &["init", "-q"]);
    git(&root, &["add", "-A"]);
    git(
        &root,
        &[
            "-c",
            "user.name=WVQ Test",
            "-c",
            "user.email=wvq@example.invalid",
            "commit",
            "-qm",
            "baseline",
        ],
    );
    TempRepo(root)
}

fn live_browser_repo(base_url: &str) -> TempRepo {
    let root = unique_temp_repo("wvq-live-browser");
    std::fs::create_dir_all(root.join("openspec/changes/live-browser/specs/ui")).unwrap();
    std::fs::create_dir_all(root.join(".weavatrix-quality/programs")).unwrap();
    std::fs::write(
        root.join(".gitignore"),
        "node_modules/\n.weavatrix-quality/*.db*\n.weavatrix-quality/cas/\n.weavatrix-quality/runtime/\n.weavatrix-quality/browser-evidence/\n.weavatrix-quality/authoring-evidence/\n",
    )
    .unwrap();
    std::fs::write(
        root.join("package.json"),
        r#"{"name":"wvq-live-browser","private":true,"dependencies":{"playwright":"1.62.1"}}"#,
    )
    .unwrap();
    link_node_modules(&root);
    std::fs::write(
        root.join("openspec/changes/live-browser/specs/ui/spec.md"),
        "# Delta for UI\n\n## ADDED Requirements\n\n### Requirement: Heading\nThe system SHALL show the WVQ heading.\n\n#### Scenario: Home\n- GIVEN the home page\n- WHEN it loads\n- THEN the WVQ heading is visible\n",
    )
    .unwrap();
    write_browser_quality(&root, "visible");
    std::fs::write(
        root.join(".weavatrix-quality/programs/home.json"),
        r#"{
  "schema_v": 1,
  "id": "home-heading",
  "source": "authored",
  "obligations": ["heading-visible"],
  "steps": [
    {"action": "navigate", "route": "/"},
    {"action": "assert", "obligation": "heading-visible"}
  ],
  "evidence_policy": {
    "screenshot": "on_failure",
    "trace": "on_failure",
    "network": "always",
    "console": "always",
    "storage": "on_failure"
  }
}"#,
    )
    .unwrap();
    std::fs::write(
        root.join(".weavatrix-quality/config.yaml"),
        format!(
            "quality_policy_v: 1\n\nbrowser:\n  base_url: {base_url}\n  engine: chromium\n  headless: true\n  timeout_ms: 30000\n  module_root: node_modules/playwright\n  programs:\n    - .weavatrix-quality/programs/home.json\n"
        ),
    )
    .unwrap();
    git(&root, &["init", "-q"]);
    git(&root, &["add", "-A"]);
    git(
        &root,
        &[
            "-c",
            "user.name=WVQ Test",
            "-c",
            "user.email=wvq@example.invalid",
            "commit",
            "-qm",
            "baseline",
        ],
    );
    TempRepo(root)
}

fn write_browser_quality(root: &Path, predicate: &str) {
    std::fs::write(
        root.join("openspec/changes/live-browser/quality.yaml"),
        format!(
            "quality_contract_v: 1\nchange: live-browser\n\nrisk:\n  default: high\n\nrequirements:\n  - capability: ui\n    requirement: heading\n    scenarios:\n      - scenario: home\n        obligations:\n          - id: heading-visible\n            kind: behavioral\n            expected:\n              kind: {predicate}\n              target:\n                role: heading\n                accessible_name: WVQ live browser\n        evidence:\n          required: [dom]\n          on_failure: [screenshot, trace]\n"
        ),
    )
    .unwrap();
}

fn link_node_modules(root: &Path) {
    let source = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("js/playwright-runner/node_modules");
    let target = root.join("node_modules");
    #[cfg(windows)]
    {
        let output = ProcessCommand::new("powershell.exe")
            .args([
                "-NoProfile",
                "-NonInteractive",
                "-Command",
                "New-Item -ItemType Junction -Path $env:WVQ_TEST_LINK_TARGET -Target $env:WVQ_TEST_LINK_SOURCE | Out-Null",
            ])
            .env("WVQ_TEST_LINK_TARGET", &target)
            .env("WVQ_TEST_LINK_SOURCE", &source)
            .output()
            .expect("PowerShell starts");
        assert!(
            output.status.success(),
            "create junction: {}",
            String::from_utf8_lossy(&output.stderr)
        );
        assert!(
            target.join("playwright/package.json").is_file(),
            "junction {} -> {} did not expose Playwright; link target: {:?}",
            target.display(),
            source.display(),
            std::fs::read_link(&target)
        );
    }
    #[cfg(unix)]
    std::os::unix::fs::symlink(source, target).unwrap();
}

fn git(root: &Path, args: &[&str]) {
    let output = ProcessCommand::new("git")
        .args(args)
        .current_dir(root)
        .output()
        .expect("git starts");
    assert!(
        output.status.success(),
        "git {}: {}",
        args.join(" "),
        String::from_utf8_lossy(&output.stderr)
    );
}

fn read_http_request(stream: &mut impl Read) -> Vec<u8> {
    let mut request = Vec::new();
    let mut buffer = [0_u8; 1024];
    let mut expected = None;
    loop {
        let read = stream.read(&mut buffer).unwrap();
        assert_ne!(read, 0, "request closed before its body was complete");
        request.extend_from_slice(&buffer[..read]);
        if expected.is_none()
            && let Some(split) = request.windows(4).position(|window| window == b"\r\n\r\n")
        {
            let head = String::from_utf8_lossy(&request[..split]);
            let content_length = head
                .lines()
                .find_map(|line| {
                    line.strip_prefix("Content-Length:")
                        .and_then(|value| value.trim().parse::<usize>().ok())
                })
                .unwrap();
            expected = Some(split + 4 + content_length);
        }
        if expected.is_some_and(|expected| request.len() >= expected) {
            return request;
        }
    }
}

struct BrowserFixtureServer {
    address: std::net::SocketAddr,
    stop: Arc<AtomicBool>,
    thread: Option<thread::JoinHandle<()>>,
}

impl BrowserFixtureServer {
    fn start() -> Self {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        listener.set_nonblocking(true).unwrap();
        let address = listener.local_addr().unwrap();
        let stop = Arc::new(AtomicBool::new(false));
        let server_stop = Arc::clone(&stop);
        let thread = thread::spawn(move || {
            while !server_stop.load(Ordering::Acquire) {
                match listener.accept() {
                    Ok((stream, _)) => {
                        thread::spawn(move || respond_browser_fixture(stream));
                    }
                    Err(err) if err.kind() == std::io::ErrorKind::WouldBlock => {
                        thread::sleep(Duration::from_millis(5));
                    }
                    Err(err) => panic!("browser fixture server: {err}"),
                }
            }
        });
        Self {
            address,
            stop,
            thread: Some(thread),
        }
    }

    fn url(&self) -> String {
        format!("http://{}", self.address)
    }
}

fn respond_browser_fixture(mut stream: std::net::TcpStream) {
    let _ = stream.set_read_timeout(Some(Duration::from_secs(2)));
    let mut request = [0_u8; 4096];
    let _ = stream.read(&mut request);
    let body = b"<!doctype html><html><body><h1>WVQ live browser</h1></body></html>";
    write!(
        stream,
        "HTTP/1.1 200 OK\r\nContent-Type: text/html\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
        body.len()
    )
    .unwrap();
    stream.write_all(body).unwrap();
    stream.flush().unwrap();
}

impl Drop for BrowserFixtureServer {
    fn drop(&mut self) {
        self.stop.store(true, Ordering::Release);
        if let Some(thread) = self.thread.take() {
            thread.join().unwrap();
        }
    }
}

#[test]
fn context_reply_is_bounded_by_token_budget() {
    let fake = FakeService::default();
    fake.set_context_items(vec![
        "requirement alpha is a long neighbouring clause about overflow".into(),
        "requirement beta is another neighbouring clause about grouping".into(),
        "obligation others-visible".into(),
        "heuristic: 0 runtime LLM tokens".into(),
    ]);
    let reply = fake
        .context(&ContextCommand {
            change: "sankey-others".into(),
            purpose: "implementation".into(),
            token_budget: 8,
        })
        .unwrap();
    assert!(reply.truncated);
    assert!(reply.tokens_used <= 8);
    let total = reply.requirements.len()
        + reply.obligations.len()
        + reply.heuristics.len()
        + reply.coverage.len();
    assert!(total < 4, "budget must drop later items");
}

#[test]
fn unknown_purpose_fails_closed() {
    let fake = FakeService::default();
    let err = fake
        .context(&ContextCommand {
            change: "sankey-others".into(),
            purpose: "vibes".into(),
            token_budget: 4000,
        })
        .unwrap_err();
    assert!(matches!(
        err,
        BusError::Unknown {
            field: "purpose",
            ..
        }
    ));
}

#[test]
fn plan_does_not_execute() {
    let fake = FakeService::default();
    let reply = fake
        .plan(&PlanCommand {
            change: "sankey-others".into(),
        })
        .unwrap();
    assert!(!reply.executed);
    assert!(!fake.run_was_executed());
    let _ = fake
        .run(&RunCommand {
            change: "sankey-others".into(),
            scope: "impacted".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert!(fake.run_was_executed());
}

#[test]
fn unknown_scope_fails_closed() {
    let fake = FakeService::default();
    let err = fake
        .run(&RunCommand {
            change: "current".into(),
            scope: "everything-everywhere".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap_err();
    assert!(matches!(err, BusError::Unknown { field: "scope", .. }));
}

#[test]
fn large_evidence_is_handle_only() {
    let fake = FakeService::default();
    let blob = vec![b'x'; INLINE_LIMIT + 16];
    fake.put_evidence("cas:big", blob);
    let reply = fake
        .evidence(&EvidenceCommand {
            handle: "cas:big".into(),
        })
        .unwrap();
    assert_eq!(reply.handle, "cas:big");
    assert!(reply.byte_len > INLINE_LIMIT as u64);
    assert!(reply.inline_text.is_none());
    assert!(reply.content_hash.is_some());
}

#[test]
fn small_utf8_evidence_is_inlined() {
    let fake = FakeService::default();
    fake.put_evidence("cas:tiny", b"junit snippet".to_vec());
    let reply = fake
        .evidence(&EvidenceCommand {
            handle: "cas:tiny".into(),
        })
        .unwrap();
    assert_eq!(reply.inline_text.as_deref(), Some("junit snippet"));
}

#[test]
fn contradicted_verify_is_blocking() {
    let fake = FakeService::default();
    fake.set_verdict("CONTRADICTED");
    let reply = dispatch(
        &fake,
        Command::Verify(VerifyCommand {
            change: "sankey-others".into(),
        }),
    )
    .unwrap();
    let Reply::Verify(body) = reply else {
        panic!("expected verify reply");
    };
    assert!(body.blocking);
    assert_eq!(body.exit_code(), 2);
    assert_eq!(body.verdict, "CONTRADICTED");
}

#[test]
fn proven_verify_is_zero_exit() {
    let fake = FakeService::default();
    fake.set_verdict("PROVEN");
    let reply = fake
        .verify(&VerifyCommand {
            change: "sankey-others".into(),
        })
        .unwrap();
    assert!(!reply.blocking);
    assert_eq!(reply.exit_code(), 0);
}

#[test]
fn explain_unknown_id_is_not_found() {
    let fake = FakeService::default();
    let err = fake
        .explain(&ExplainCommand {
            id: "missing".into(),
        })
        .unwrap_err();
    assert!(matches!(err, BusError::NotFound(_)));
}

#[test]
fn live_spec_validate_and_seal_sankey_others() {
    let service = LiveService::new(fixture_repo());
    let change = SpecCommand {
        change: "sankey-others".into(),
    };
    let valid = service.spec_validate(&change).unwrap();
    assert!(valid.ok);
    assert_eq!(valid.change, "sankey-others");
    assert!(valid.obligations >= 4);
    let sealed = service.spec_seal(&change).unwrap();
    assert!(sealed.seal_id.starts_with("oseal-"));
    assert_eq!(sealed.digest.len(), 64);
}

#[test]
fn live_current_change_is_ambiguous_in_fixture_repo() {
    let service = LiveService::new(fixture_repo());
    let err = service
        .spec_validate(&SpecCommand {
            change: "current".into(),
        })
        .unwrap_err();
    assert!(matches!(err, BusError::Ambiguous(_)));
}

#[test]
fn live_verify_without_runtime_is_unproven_not_failed() {
    let service = LiveService::new(fixture_repo());
    let reply = service
        .verify(&VerifyCommand {
            change: "sankey-others".into(),
        })
        .unwrap();
    assert_eq!(reply.verdict, "UNPROVEN");
    assert!(!reply.blocking);
    assert_eq!(reply.exit_code(), 1);
    assert!(reply.proofs.iter().all(|item| item.verdict == "UNPROVEN"));
}

#[test]
fn live_select_unions_base_and_head_static_candidates() {
    let repo = live_runner_repo();
    std::fs::write(
        repo.0.join("src/lib.rs"),
        "pub fn add(a: i32, b: i32) -> i32 { a.saturating_add(b) }\n",
    )
    .unwrap();
    let service = LiveService::new(&repo.0);
    let reply = service
        .select(&SelectCommand {
            change: "live-add".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert!(!reply.executed);
    assert_eq!(
        reply.algorithm,
        "weavatrix-base-head-history-union+greedy-weighted-set-cover"
    );
    assert!(reply.revision.is_some());
    assert!(
        reply.selected.contains(&"tests/addition.rs".into()),
        "{:?}",
        reply.selected
    );
    assert!(reply.uncovered_mandatory.is_empty());
    assert!(reply.selection_complete);
}

#[test]
fn live_debt_uses_an_immutable_git_baseline() {
    let repo = live_runner_repo();
    let service = LiveService::new(&repo.0);
    let reply = service
        .debt(&wvq_command_bus::DebtCommand {
            change: "live-add".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert!(reply.comparison_present);
    assert!(reply.revision.is_some());
    assert_eq!(reply.new, 0);
    assert_eq!(reply.fixed, 0);
}

#[test]
fn live_run_accepts_an_exact_committed_pr_range() {
    let repo = live_runner_repo();
    std::fs::write(
        repo.0.join("src/lib.rs"),
        "/// Checked-in head.\npub fn add(a: i32, b: i32) -> i32 { a + b }\n",
    )
    .unwrap();
    git(&repo.0, &["add", "-A"]);
    git(
        &repo.0,
        &[
            "-c",
            "user.name=WVQ Test",
            "-c",
            "user.email=wvq@example.invalid",
            "commit",
            "-qm",
            "feature head",
        ],
    );
    let service = LiveService::new(&repo.0);
    let reply = service
        .run(&RunCommand {
            change: "live-add".into(),
            scope: "all".into(),
            evidence_policy: "minimal".into(),
            base: "HEAD~1".into(),
            head: "HEAD".into(),
        })
        .unwrap();
    assert_eq!(reply.base, "HEAD~1");
    assert_eq!(reply.head, "HEAD");
    assert_eq!(reply.outcome, "passed");
}

#[test]
fn explicit_committed_head_rejects_a_dirty_worktree() {
    let repo = live_runner_repo();
    std::fs::write(
        repo.0.join("src/lib.rs"),
        "pub fn add(a: i32, b: i32) -> i32 { a.saturating_add(b) }\n",
    )
    .unwrap();
    let service = LiveService::new(&repo.0);
    let err = service
        .select(&SelectCommand {
            change: "live-add".into(),
            base: "HEAD~1".into(),
            head: "HEAD".into(),
        })
        .unwrap_err();
    assert!(err.to_string().contains("dirty worktree"), "{err}");
}

#[test]
fn live_recovery_is_populated_from_git_and_weavatrix() {
    let repo = live_runner_repo();
    std::fs::write(
        repo.0.join("src/lib.rs"),
        "/// Checked implementation.\npub fn add(a: i32, b: i32) -> i32 { a.saturating_add(b) }\n",
    )
    .unwrap();
    let service = LiveService::new(&repo.0);
    let desk = service
        .recovery_desk("live-add", "HEAD", "WORKTREE")
        .unwrap();
    let packet = desk.packet().expect("live recovery packet");
    assert_eq!(packet.base_revision.len(), 40);
    assert!(packet.head_revision.contains("WORKTREE@"));
    assert!(!packet.code_delta_summary.changed_symbols.is_empty());
    assert!(!packet.capability_clusters.is_empty());
    assert_eq!(desk.review().change, "live-add");
}

#[test]
fn live_protection_replays_base_and_head_coverage() {
    let repo = live_coverage_runner_repo();
    std::fs::write(
        repo.0.join("src/add.js"),
        "export function add(a, b) {\n  return Number(a) + Number(b);\n}\n",
    )
    .unwrap();
    let service = LiveService::new(&repo.0);
    let view = service
        .protection_view("live-js", "HEAD", "WORKTREE")
        .unwrap();
    assert!(
        !view.flows.is_empty(),
        "live coverage must create flow views"
    );
    assert!(
        view.deltas
            .iter()
            .any(|delta| delta.state.as_str() == "preserved"),
        "same measured branch should be preserved: {:?}",
        view.deltas
    );
    assert!(!view.report().blocking);
}

#[test]
fn live_model_call_charges_persistent_per_change_budget() {
    let repo = live_runner_repo();
    let listener = TcpListener::bind("127.0.0.1:0").unwrap();
    let address = listener.local_addr().unwrap();
    std::fs::write(
        repo.0.join(".weavatrix-quality/config.yaml"),
        format!(
            "quality_policy_v: 1\n\ntest_bindings:\n  - path: tests/addition.rs\n    obligations: [addition-suite]\n    cost: 10\n    flake_penalty: 0\n\nai:\n  endpoint: http://{address}/v1/chat/completions\n  model: local-test\n  max_output_tokens: 8\n  max_tokens_per_change: 15\n  max_runtime_tokens: 100\n  max_browser_escape_calls: 1\n  max_vision_calls: 1\n  max_cost_micros: 100\n  input_micros_per_million: 1000000\n  output_micros_per_million: 2000000\n"
        ),
    )
    .unwrap();
    let server = thread::spawn(move || {
        let (mut stream, _) = listener.accept().unwrap();
        let request = read_http_request(&mut stream);
        assert!(
            String::from_utf8_lossy(&request).starts_with("POST /v1/chat/completions HTTP/1.1")
        );
        let body = br#"{"model":"local-test","choices":[{"message":{"content":"inspect boundary"}}],"usage":{"prompt_tokens":3,"completion_tokens":2}}"#;
        write!(
            stream,
            "HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nContent-Length: {}\r\nConnection: close\r\n\r\n",
            body.len()
        )
        .unwrap();
        stream.write_all(body).unwrap();
    });
    let first = LiveService::new(&repo.0)
        .model(&ModelCommand {
            change: "live-add".into(),
            kind: "planning".into(),
            prompt: "probe".into(),
        })
        .unwrap();
    server.join().unwrap();
    assert_eq!(first.text, "inspect boundary");
    assert_eq!(first.input_tokens + first.output_tokens, 5);
    assert_eq!(first.cost_micros, 7);

    let error = LiveService::new(&repo.0)
        .model(&ModelCommand {
            change: "live-add".into(),
            kind: "planning".into(),
            prompt: "second probe".into(),
        })
        .unwrap_err();
    assert!(matches!(error, BusError::Model(_)));
    assert!(error.to_string().contains("AI_BUDGET_EXHAUSTED"));
}

#[test]
fn live_plan_sets_executed_false() {
    let service = LiveService::new(fixture_repo());
    let reply = service
        .plan(&PlanCommand {
            change: "sankey-others".into(),
        })
        .unwrap();
    assert!(!reply.executed);
    assert!(!reply.gaps.is_empty());
    assert!(reply.checks.contains(&"coverage".into()));
}

#[test]
fn live_run_rejects_a_repo_without_a_supported_runner() {
    let service = LiveService::new(fixture_repo());
    let err = service
        .run(&RunCommand {
            change: "sankey-others".into(),
            scope: "impacted".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap_err();
    assert!(
        err.to_string().contains("no supported registered executor"),
        "unexpected error: {err}"
    );
}

#[test]
#[allow(clippy::too_many_lines)]
fn live_run_executes_persists_and_proves_a_real_registered_suite() {
    let repo = live_runner_repo();
    std::fs::write(
        repo.0.join("src/lib.rs"),
        "/// Add two integers.\npub fn add(a: i32, b: i32) -> i32 { a + b }\n",
    )
    .unwrap();
    let service = LiveService::new(&repo.0);
    let reply = service
        .run(&RunCommand {
            change: "live-add".into(),
            scope: "impacted".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert!(reply.executed);
    assert_eq!(reply.outcome, "passed");
    assert_eq!(reply.requested_scope, "impacted");
    assert_eq!(reply.scope, "all", "incomplete selection must widen safely");
    assert!(
        reply
            .artifact_handles
            .iter()
            .any(|handle| handle.ends_with("-summary"))
    );
    assert!(
        reply
            .artifact_handles
            .iter()
            .any(|handle| handle.ends_with("-graph-diff"))
    );
    assert!(
        reply
            .artifact_handles
            .iter()
            .any(|handle| handle.ends_with("-impact"))
    );

    let reopened = LiveService::new(&repo.0);
    let status = reopened
        .status(&wvq_command_bus::StatusCommand {
            run_id: Some(reply.run_id.clone()),
        })
        .unwrap();
    assert_eq!(status.outcome.as_deref(), Some("passed"));
    assert_eq!(status.handles, reply.artifact_handles);

    let summary = reopened
        .evidence(&EvidenceCommand {
            handle: reply
                .artifact_handles
                .iter()
                .find(|handle| handle.ends_with("-summary"))
                .unwrap()
                .clone(),
        })
        .unwrap();
    assert_eq!(summary.kind, "execution-summary");
    assert!(
        summary
            .inline_text
            .as_deref()
            .unwrap()
            .contains("cargo-test")
    );

    let impact = reopened
        .evidence(&EvidenceCommand {
            handle: reply
                .artifact_handles
                .iter()
                .find(|handle| handle.ends_with("-impact"))
                .unwrap()
                .clone(),
        })
        .unwrap();
    assert_eq!(impact.kind, "impacted-surface");
    assert!(impact.inline_text.is_some());

    let verified = reopened
        .verify(&VerifyCommand {
            change: "live-add".into(),
        })
        .unwrap();
    assert_eq!(verified.verdict, "PROVEN");
    assert_eq!(verified.exit_code(), 0);

    let planned = reopened
        .plan(&PlanCommand {
            change: "live-add".into(),
        })
        .unwrap();
    assert_eq!(planned.existing_proofs.len(), 1);
    assert!(planned.gaps.is_empty(), "{:?}", planned.gaps);
    let proof = reopened
        .explain(&ExplainCommand {
            id: planned.existing_proofs[0].clone(),
        })
        .unwrap();
    assert_eq!(proof.kind, "proof");
    assert!(
        proof
            .provenance
            .iter()
            .any(|item| item.starts_with("revision "))
    );

    let run = reopened
        .explain(&ExplainCommand {
            id: reply.run_id.clone(),
        })
        .unwrap();
    assert_eq!(run.kind, "run");
    assert!(run.summary.contains("passed"));

    let selection = reopened
        .explain(&ExplainCommand {
            id: "tests/addition.rs".into(),
        })
        .unwrap();
    assert_eq!(selection.kind, "selection");
    assert!(!selection.provenance.is_empty());
}

#[test]
fn a_green_suite_without_an_obligation_binding_is_not_proof() {
    let repo = live_runner_repo();
    std::fs::remove_file(repo.0.join(".weavatrix-quality/config.yaml")).unwrap();
    git(&repo.0, &["add", "-A"]);
    git(
        &repo.0,
        &[
            "-c",
            "user.name=WVQ Test",
            "-c",
            "user.email=wvq@example.invalid",
            "commit",
            "-qm",
            "remove binding",
        ],
    );
    let service = LiveService::new(&repo.0);
    let run = service
        .run(&RunCommand {
            change: "live-add".into(),
            scope: "all".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert_eq!(run.outcome, "passed");

    let verified = service
        .verify(&VerifyCommand {
            change: "live-add".into(),
        })
        .unwrap();
    assert_eq!(verified.verdict, "UNPROVEN");
    assert_eq!(verified.exit_code(), 1);
}

#[test]
fn live_browser_program_proves_and_contradicts_the_sealed_oracle() {
    let _browser_guard = BROWSER_TEST_LOCK
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    let server = BrowserFixtureServer::start();
    let repo = live_browser_repo(&server.url());
    let service = LiveService::new(&repo.0);
    let run = service
        .run(&RunCommand {
            change: "live-browser".into(),
            scope: "all".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert_eq!(run.outcome, "passed");
    assert!(
        run.artifact_handles
            .iter()
            .any(|handle| handle.contains("browser-0-home-heading")),
        "{:?}",
        run.artifact_handles
    );
    let proven = service
        .verify(&VerifyCommand {
            change: "live-browser".into(),
        })
        .unwrap();
    assert_eq!(proven.verdict, "PROVEN", "{:?}", proven.proofs);

    write_browser_quality(&repo.0, "hidden");
    let contradicted_run = service
        .run(&RunCommand {
            change: "live-browser".into(),
            scope: "all".into(),
            evidence_policy: "standard".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
        })
        .unwrap();
    assert_eq!(contradicted_run.outcome, "failed");
    assert!(
        contradicted_run
            .artifact_handles
            .iter()
            .any(|handle| handle.contains("screenshot")),
        "failure screenshot must be returned as a handle: {:?}",
        contradicted_run.artifact_handles
    );
    assert!(
        contradicted_run
            .artifact_handles
            .iter()
            .any(|handle| handle.contains("trace")),
        "failure trace must be returned as a handle: {:?}",
        contradicted_run.artifact_handles
    );
    let contradicted = service
        .verify(&VerifyCommand {
            change: "live-browser".into(),
        })
        .unwrap();
    assert_eq!(contradicted.verdict, "CONTRADICTED");
    assert!(contradicted.blocking);
}

#[test]
#[allow(clippy::too_many_lines)]
fn authoring_promotes_only_the_exact_passing_playwright_preview() {
    let _browser_guard = BROWSER_TEST_LOCK
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    let server = BrowserFixtureServer::start();
    let repo = live_browser_repo(&server.url());
    std::fs::write(
        repo.0.join(".weavatrix-quality/config.yaml"),
        format!(
            "quality_policy_v: 1\n\nbrowser:\n  base_url: {}\n  engine: chromium\n  headless: true\n  timeout_ms: 30000\n  module_root: node_modules/playwright\n",
            server.url()
        ),
    )
    .unwrap();
    std::fs::write(
        repo.0.join("package.json"),
        r#"{"name":"wvq-live-browser","private":true,"dependencies":{"playwright":"1.62.1"},"description":"changed UI"}"#,
    )
    .unwrap();
    let service = LiveService::new(&repo.0);
    let draft = service
        .author_draft(&AuthorDraftCommand {
            change: "live-browser".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
            token_budget: 8_000,
            use_model: false,
        })
        .unwrap();
    assert!(!draft.revision.is_empty());
    assert!(draft.changed_files.contains(&"package.json".into()));
    assert_eq!(draft.obligations[0].id, "heading-visible");
    assert!(draft.obligations[0].expected.is_some());
    assert!(draft.candidate.is_none());

    let program = serde_json::json!({
        "schema_v": 1,
        "id": "generated-home-heading",
        "source": "generated",
        "obligations": ["heading-visible"],
        "steps": [
            {"action": "navigate", "route": "/"},
            {"action": "assert", "obligation": "heading-visible"}
        ]
    });
    let validated = service
        .author_validate(&AuthorValidateCommand {
            change: "live-browser".into(),
            program: program.clone(),
        })
        .unwrap();
    assert!(validated.valid);
    assert!(!validated.persisted);
    assert!(validated.seal_id.starts_with("oseal-"));

    let preview = service
        .author_preview(&AuthorPreviewCommand {
            change: "live-browser".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
            program: program.clone(),
            screenshot: true,
            trace: true,
        })
        .unwrap();
    assert!(preview.passed, "{:?}", preview.failure);
    assert!(!preview.preview_id.is_empty());
    assert_eq!(preview.asserted, ["heading-visible"]);
    assert!(!preview.program_persisted);
    assert_eq!(preview.screenshot_handles.len(), 2);
    assert!(preview.trace_handle.is_some());
    for handle in preview
        .observation_handles
        .iter()
        .chain(&preview.screenshot_handles)
        .chain(preview.trace_handle.iter())
    {
        service
            .evidence(&EvidenceCommand {
                handle: handle.clone(),
            })
            .unwrap();
    }
    assert!(
        !repo
            .0
            .join(".weavatrix-quality/programs/generated-home-heading.json")
            .exists()
    );

    let mut other_program = program.clone();
    other_program["id"] = serde_json::json!("different-generated-program");
    let mismatch = service
        .author_promote(&AuthorPromoteCommand {
            change: "live-browser".into(),
            preview_id: preview.preview_id.clone(),
            program: other_program,
        })
        .unwrap_err();
    assert!(mismatch.to_string().contains("does not match"), "{mismatch}");

    let promoted = service
        .author_promote(&AuthorPromoteCommand {
            change: "live-browser".into(),
            preview_id: preview.preview_id.clone(),
            program: program.clone(),
        })
        .unwrap();
    assert!(promoted.persisted);
    assert!(promoted.created);
    assert_eq!(promoted.program_revision, 1);
    assert_eq!(promoted.seal_id, validated.seal_id);

    let repeated = service
        .author_promote(&AuthorPromoteCommand {
            change: "live-browser".into(),
            preview_id: preview.preview_id,
            program,
        })
        .unwrap();
    assert!(!repeated.created);
    let store = wvq_store::Store::open(&repo.0).unwrap();
    let (record, body) = store
        .read_program_revision("generated-home-heading", 1)
        .unwrap()
        .expect("promoted program revision");
    assert_eq!(record.source, "promoted");
    let stored: serde_json::Value = serde_json::from_slice(&body).unwrap();
    assert_eq!(stored["id"], "generated-home-heading");

    let replay = service
        .run(&RunCommand {
            change: "live-browser".into(),
            base: "HEAD".into(),
            head: "WORKTREE".into(),
            scope: "all".into(),
            evidence_policy: "minimal".into(),
        })
        .unwrap();
    assert_eq!(replay.outcome, "passed");
    assert_eq!(replay.browser_programs, 1);
    assert_eq!(replay.recorded_test_count, 1);
}

#[test]
fn authoring_refuses_candidate_owned_oracle_fields() {
    let server = BrowserFixtureServer::start();
    let repo = live_browser_repo(&server.url());
    let service = LiveService::new(&repo.0);
    let error = service
        .author_validate(&AuthorValidateCommand {
            change: "live-browser".into(),
            program: serde_json::json!({
                "schema_v": 1,
                "id": "tries-to-rewrite-oracle",
                "source": "generated",
                "obligations": ["heading-visible"],
                "steps": [{"action": "assert", "obligation": "heading-visible"}],
                "expected": {"kind": "hidden", "target": {"role": "heading"}}
            }),
        })
        .unwrap_err();
    assert!(
        error.to_string().contains("unknown field `expected`"),
        "{error}"
    );
}

#[test]
fn estimate_tokens_is_stable() {
    assert_eq!(estimate_tokens(""), 0);
    assert_eq!(estimate_tokens("abcd"), 1);
    assert_eq!(estimate_tokens("abcdefgh"), 2);
}
