ALTER TABLE ai_usage ADD COLUMN change_id TEXT NOT NULL DEFAULT '';
ALTER TABLE ai_usage ADD COLUMN run_id TEXT NOT NULL DEFAULT '';
ALTER TABLE ai_usage ADD COLUMN planning_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN runtime_tokens INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN browser_escape_calls INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN vision_calls INTEGER NOT NULL DEFAULT 0;
ALTER TABLE ai_usage ADD COLUMN cost_micros INTEGER NOT NULL DEFAULT 0;

ALTER TABLE human_decisions ADD COLUMN reviewer TEXT NOT NULL DEFAULT '';
ALTER TABLE human_decisions ADD COLUMN role TEXT NOT NULL DEFAULT '';
ALTER TABLE human_decisions ADD COLUMN subject TEXT NOT NULL DEFAULT '';
ALTER TABLE human_decisions ADD COLUMN artifact_digest TEXT NOT NULL DEFAULT '';
ALTER TABLE human_decisions ADD COLUMN decision TEXT NOT NULL DEFAULT '';
ALTER TABLE human_decisions ADD COLUMN comment TEXT;
ALTER TABLE human_decisions ADD COLUMN decided_at TEXT NOT NULL DEFAULT '';
