//! Task 16: seven default tools, strict schemas, handle-based evidence, catalog budget.

use std::io::{Cursor, Write};
use std::path::{Path, PathBuf};
use std::process::Command as ProcessCommand;
use std::sync::{Arc, Mutex};
use std::time::Duration;
use std::time::{SystemTime, UNIX_EPOCH};

use mcport::{ConcurrentToolServer, RuntimeConfig, json, serve_controlled_streams};
use wvq_command_bus::{FakeService, INLINE_LIMIT, LiveService, QualityService, estimate_tokens};
use wvq_mcp::{
    HostProfile, authoring_server, catalog_token_footprint, parse_host_args, quality_server,
    runtime_config,
};

const DEFAULT_TOOLS: [&str; 7] = [
    "quality_context",
    "quality_plan",
    "quality_run",
    "quality_status",
    "quality_verify",
    "quality_explain",
    "quality_evidence",
];

fn server() -> mcport::ConcurrentMcpServer {
    let service: Arc<dyn QualityService> = Arc::new(FakeService::default());
    quality_server(&service)
}

#[derive(Clone, Default)]
struct SharedWriter(Arc<Mutex<Vec<u8>>>);

impl Write for SharedWriter {
    fn write(&mut self, bytes: &[u8]) -> std::io::Result<usize> {
        self.0.lock().unwrap().extend_from_slice(bytes);
        Ok(bytes.len())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

struct TempRepo(PathBuf);

impl Drop for TempRepo {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.0);
    }
}

fn live_repo() -> TempRepo {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_nanos();
    let root = std::env::temp_dir().join(format!("wvq-mcp-live-{nanos}"));
    for dir in [
        "src",
        "tests",
        ".weavatrix-quality",
        "openspec/changes/live/specs/arithmetic",
    ] {
        std::fs::create_dir_all(root.join(dir)).unwrap();
    }
    std::fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"wvq-mcp-live\"\nversion = \"0.0.0\"\nedition = \"2024\"\n",
    )
    .unwrap();
    std::fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"wvq-mcp-live\"\nversion = \"0.0.0\"\n",
    )
    .unwrap();
    std::fs::write(
        root.join("src/lib.rs"),
        "pub fn add(a:i32,b:i32)->i32{a+b}\n",
    )
    .unwrap();
    std::fs::write(
        root.join("tests/addition.rs"),
        "use wvq_mcp_live::add;\n#[test]\nfn adds(){assert_eq!(add(2,3),5);}\n",
    )
    .unwrap();
    std::fs::write(
        root.join("openspec/changes/live/specs/arithmetic/spec.md"),
        "# Arithmetic\n\n## ADDED Requirements\n\n### Requirement: Addition\nThe system SHALL add integers.\n\n#### Scenario: Sum\n- GIVEN two integers\n- WHEN added\n- THEN the sum is returned\n",
    )
    .unwrap();
    std::fs::write(
        root.join("openspec/changes/live/quality.yaml"),
        "quality_contract_v: 1\nchange: live\nrisk:\n  default: low\nrequirements:\n  - capability: arithmetic\n    requirement: addition\n    scenarios:\n      - scenario: sum\n        obligations:\n          - id: addition-suite\n            kind: invariant\n        evidence:\n          required: []\n          on_failure: []\n",
    )
    .unwrap();
    std::fs::write(
        root.join(".weavatrix-quality/config.yaml"),
        "quality_policy_v: 1\ntest_bindings:\n  - path: tests/addition.rs\n    runner: cargo-test\n    case: adds\n    obligations: [addition-suite]\n",
    )
    .unwrap();
    git(&root, &["init", "-q"]);
    git(&root, &["add", "-A"]);
    git(
        &root,
        &[
            "-c",
            "user.name=WVQ Test",
            "-c",
            "user.email=wvq@example.invalid",
            "commit",
            "-qm",
            "baseline",
        ],
    );
    TempRepo(root)
}

fn git(root: &Path, args: &[&str]) {
    let output = ProcessCommand::new("git")
        .args(args)
        .current_dir(root)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
}

fn protocol_call(
    service: &Arc<dyn QualityService>,
    name: &str,
    arguments: &serde_json::Value,
) -> String {
    protocol_call_server(quality_server(service), name, arguments)
}

fn protocol_call_server(
    server: mcport::ConcurrentMcpServer,
    name: &str,
    arguments: &serde_json::Value,
) -> String {
    let request = serde_json::json!({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "tools/call",
        "params": {"name": name, "arguments": arguments}
    });
    let input = Cursor::new(format!("{request}\n").into_bytes());
    let writer = SharedWriter::default();
    let captured = writer.clone();
    serve_controlled_streams(Arc::new(server), input, writer, runtime_config()).unwrap();
    let bytes = captured.0.lock().unwrap().clone();
    String::from_utf8(bytes).unwrap()
}

#[test]
fn authoring_profile_exposes_only_five_high_level_playwright_tools() {
    let service: Arc<dyn QualityService> = Arc::new(FakeService::default());
    let built = authoring_server(&service, "live", "HEAD", "WORKTREE");
    let catalog = built.catalog();
    let names = catalog
        .as_array()
        .unwrap()
        .iter()
        .map(|tool| tool["name"].as_str().unwrap())
        .collect::<Vec<_>>();
    assert_eq!(
        names,
        [
            "quality_test_draft",
            "quality_test_validate",
            "quality_test_preview",
            "quality_test_promote",
            "quality_test_heal"
        ]
    );
    assert!(built.schema_defects().is_empty());
    for banned in [
        "browser_click",
        "browser_navigate",
        "javascript_eval",
        "shell",
    ] {
        assert!(!names.contains(&banned));
    }
}

#[test]
fn host_selects_the_authoring_profile_and_fixed_revision_range() {
    let options = parse_host_args(&[
        "--profile".into(),
        "authoring".into(),
        "--change".into(),
        "live".into(),
        "--base".into(),
        "origin/main".into(),
        "--head".into(),
        "WORKTREE".into(),
    ])
    .unwrap();
    assert_eq!(options.profile, HostProfile::Authoring);
    assert_eq!(options.change, "live");
    assert_eq!(options.base, "origin/main");
    assert_eq!(options.head, "WORKTREE");
}

#[test]
fn authoring_profile_runs_the_shared_command_bus_with_fixed_scope() {
    let service: Arc<dyn QualityService> = Arc::new(FakeService::default());
    let draft = protocol_call_server(
        authoring_server(&service, "live", "BASE", "HEAD"),
        "quality_test_draft",
        &serde_json::json!({"token_budget": 8000}),
    );
    assert!(draft.contains("\"change\":\"live\""), "{draft}");
    assert!(draft.contains("\"base\":\"BASE\""), "{draft}");
    assert!(draft.contains("\"candidate\":null"), "{draft}");

    let validated = protocol_call_server(
        authoring_server(&service, "live", "BASE", "HEAD"),
        "quality_test_validate",
        &serde_json::json!({"program": {"id": "generated-program"}}),
    );
    assert!(validated.contains("\"valid\":true"), "{validated}");
    assert!(validated.contains("\"persisted\":false"), "{validated}");

    let promoted = protocol_call_server(
        authoring_server(&service, "live", "BASE", "HEAD"),
        "quality_test_promote",
        &serde_json::json!({
            "preview_id": "preview-generated-program",
            "program": {"id": "generated-program"}
        }),
    );
    assert!(promoted.contains("\"program_revision\":1"), "{promoted}");
    assert!(promoted.contains("\"persisted\":true"), "{promoted}");

    let healed = protocol_call_server(
        authoring_server(&service, "live", "BASE", "HEAD"),
        "quality_test_heal",
        &serde_json::json!({
            "program_id": "generated-program",
            "expected_program_revision": 1,
            "edits": [{
                "edit": "insert_wait",
                "after": 0,
                "condition": {"kind": "url", "route": "/ready"}
            }]
        }),
    );
    assert!(healed.contains("\"program_revision\":2"), "{healed}");
    assert!(healed.contains("\"persisted\":true"), "{healed}");
}

#[test]
fn default_profile_exposes_exactly_seven_tools() {
    let catalog = server().catalog();
    let tools = catalog.as_array().expect("tool catalog is an array");
    let names: Vec<&str> = tools
        .iter()
        .map(|tool| {
            tool.get("name")
                .and_then(mcport::Value::as_str)
                .unwrap_or("")
        })
        .collect();
    assert_eq!(names, DEFAULT_TOOLS);
    for banned in [
        "quality_select",
        "quality_explore",
        "quality_mutate",
        "quality_replay",
        "browser_click",
        "shell",
    ] {
        assert!(
            !names.contains(&banned),
            "default profile must not expose {banned}"
        );
    }
}

#[test]
fn strict_schemas_have_no_defects() {
    let built = server();
    assert!(
        built.schema_defects().is_empty(),
        "strict catalog defects: {:?}",
        built.schema_defects()
    );
}

#[test]
fn tool_schema_token_footprint_stays_small() {
    let built = server();
    let tokens = catalog_token_footprint(&built);
    let bytes = built.catalog().to_string().len();
    assert!(
        tokens < 2_000,
        "catalog token footprint {tokens} (bytes {bytes}) is too large for a coding-agent profile"
    );
    assert!(tokens > 50, "catalog should describe the seven tools");
}

#[test]
fn runtime_uses_controlled_concurrency_and_deadlines() {
    let config = runtime_config();
    assert_eq!(config.max_in_flight, 4);
    assert_eq!(config.queue_depth, 32);
    assert_eq!(config.handler_deadline, Some(Duration::from_secs(16 * 60)));
    let _ = RuntimeConfig::default();
}

#[test]
fn quality_context_is_bounded() {
    let fake = FakeService::default();
    fake.set_context_items(
        (0..40)
            .map(|index| format!("requirement clause {index} with neighbouring intent text"))
            .collect(),
    );
    let reply = fake
        .context(&wvq_command_bus::ContextCommand {
            change: "sankey-others".into(),
            purpose: "spec".into(),
            token_budget: 12,
        })
        .unwrap();
    assert!(reply.truncated);
    assert!(reply.tokens_used <= 12);
}

#[test]
fn quality_evidence_keeps_large_blobs_as_handles() {
    let fake = FakeService::default();
    fake.put_evidence("shot-1", vec![0_u8; INLINE_LIMIT + 8]);
    let reply = fake
        .evidence(&wvq_command_bus::EvidenceCommand {
            handle: "shot-1".into(),
        })
        .unwrap();
    assert!(reply.inline_text.is_none());
    let encoded = serde_json::to_string(&reply).unwrap();
    assert!(
        encoded.len() < 1_000,
        "large evidence must not dump blob bytes into the MCP reply"
    );
    assert!(estimate_tokens(&encoded) < 200);
}

#[test]
fn catalog_descriptors_are_honest_objects() {
    let catalog = server().catalog();
    for tool in catalog.as_array().unwrap() {
        let schema = tool.get("inputSchema").expect("inputSchema");
        assert_eq!(
            schema.get("type").and_then(mcport::Value::as_str),
            Some("object")
        );
        assert!(schema.get("properties").is_some());
        let _ = json!({"ok": true});
    }
}

#[test]
fn quality_run_schema_exposes_the_exact_revision_range() {
    let catalog = server().catalog();
    let run = catalog
        .as_array()
        .unwrap()
        .iter()
        .find(|tool| tool["name"] == "quality_run")
        .expect("quality_run");
    let properties = run["inputSchema"]["properties"].as_object().unwrap();
    assert!(properties.contains_key("base"));
    assert!(properties.contains_key("head"));
}

#[test]
fn live_mcp_run_status_and_verify_execute_the_shared_command_bus() {
    let repo = live_repo();
    let service: Arc<dyn QualityService> = Arc::new(LiveService::new(&repo.0));
    let run = protocol_call(
        &service,
        "quality_run",
        &serde_json::json!({"change": "live", "scope": "all", "evidence_policy": "standard"}),
    );
    assert!(run.contains("\"executed\":true"), "{run}");
    assert!(run.contains("\"outcome\":\"passed\""), "{run}");

    let status = protocol_call(&service, "quality_status", &serde_json::json!({}));
    assert!(status.contains("\"outcome\":\"passed\""), "{status}");

    let verify = protocol_call(
        &service,
        "quality_verify",
        &serde_json::json!({"change": "live"}),
    );
    assert!(verify.contains("PROVEN"), "{verify}");
}
